[nanobot]
config_version = 1

[logging]
level = "DEBUG"

[database]
connection = "build/nanobot.db"

[assets]
path = "build/"

[templates]
path = "src/templates/"

[actions.rebuild]
label = "Rebuild New Organism Tree (~10s)"
commands = [
  ["make", "save"],
  ["make", "build/organism-tree.built"],
  ["make", "reload"]
]

[actions.owl]
label = "Rebuild New Organism Tree OWL file (~60s)"
commands = [
  ["make", "save"],
  ["make", "build/organism-tree.owl"],
  ["make", "reload"]
]