[nanobot]
config_version = 1

[logging]
level = "DEBUG"

[database]
connection = "nanobot.db"

[assets]
path = "."

[valve]
path = "../../src/arborist/table.tsv"

[templates]
path = "../../src/templates/"

[actions.rebuild_organism]
label = "Rebuild New Organism Tree (~10s)"
commands = [
  ["make", "save"],
  ["make", "build/organism-tree.built"],
  ["make", "reload"]
]

[actions.rebuild_subspecies]
label = "Rebuild New Subspecies Tree (~20s)"
commands = [
  ["make", "save"],
  ["make", "build/subspecies-tree.built"],
]

[actions.rebuild_organism_owl]
label = "Rebuild New Organism Tree OWL file (~1m)"
commands = [
  ["make", "save"],
  ["make", "build/organism-tree.owl"],
  ["make", "reload"]
]

[actions.rebuild_subspecies_owl]
label = "Rebuild New Subspecies Tree OWL file (~6m)"
commands = [
  ["make", "save"],
  ["make", "build/subspecies-tree.owl"],
]
