stages:
  - test

variables:
  PYTHONPATH: "."

pytest:
  stage: test
  image: python:3.9
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - apt-get update -y
    - apt-get install -y wget
    - wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.14.1+-x64-linux.tar.gz
    - tar xzf ncbi-blast-2.14.1+-x64-linux.tar.gz
    - mv ncbi-blast-2.14.1+/bin/* /usr/bin/
    - wget http://eddylab.org/software/hmmer/hmmer-3.3.2.tar.gz
    - tar xzf hmmer-3.3.2.tar.gz
    - cd hmmer-3.3.2 && ./configure && make && mv src/hmmscan /usr/bin/ && cd ..
  script:
    - pytest
