#!/bin/sh

# Fetch the IEDB data required by Arborist as TSV.

DATABASE=${DATABASE:-$1}
DATABASE=${DATABASE:?'Please provide a database name'}
CACHE="cache/iedb/${DATABASE}"

fail() {
  echo "ERROR: $1"
  exit 1
}

if [ -d "${CACHE}" ]; then
  fail "${CACHE} already exists"
fi

mkdir -p "${CACHE}/"
export MYSQL_DATABASE="${DATABASE}"

fetch() {
  NAME="$1"
  SQL="$2"
  FILE="${CACHE}/${NAME}.tsv"
  echo "Fetching ${FILE}.gz"
  src/util/mysql2tsv "${SQL}" "${FILE}" || fail "Failed to fetch ${NAME}"
  gzip "${FILE}" || fail "Failed to compress ${FILE}"
}

fetch ncbi_include \
	"SELECT ncbi_organism_id AS taxon_id FROM ncbi_organism_include WHERE ncbi_organism_id < 10000000 ORDER BY taxon_id"

fetch iedb_taxa "SELECT * FROM iedb_taxa_view ORDER BY iedb_id"

for TABLE in epitope source object; do
  fetch "${TABLE}" "SELECT * FROM ${TABLE} ORDER BY ${TABLE}_id"
done

echo "Linking current/iedb/ to ${CACHE}"
mkdir -p current
cd current || fail 'Could not cd to current/'
rm -f iedb
ln -s "../${CACHE}" iedb
