#!/bin/sh

# Fetch the IEDB data required by Arborist as TSV,
# cache it in a named directory,
# and update the `current/iedb` symlink.

NAME=${1:?'Please provide a cache directory name'}
CACHE="cache/iedb/${NAME}"

if [ -d "${CACHE}" ]; then
  echo "ERROR: ${CACHE} already exists"
  exit 1
fi

mkdir -p "${CACHE}/" || exit 1

fail() {
  echo "ERROR: $1"
  echo "Removing ${CACHE}"
  rm -rf "${CACHE}"
  exit 1
}

fetch() {
  NAME="$1"
  SQL="$2"
  FILE="${CACHE}/${NAME}.tsv"
  echo "Fetching ${FILE}.gz"
  src/util/mysql2tsv "${SQL}" "${FILE}" || fail "Failed to fetch ${NAME}"
  gzip "${FILE}" || fail "Failed to compress ${FILE}"
}

fetch ncbi_include \
	"SELECT ncbi_organism_id AS taxon_id FROM ncbi_organism_include WHERE ncbi_organism_id < 10000000 ORDER BY taxon_id"

fetch iedb_taxa "SELECT * FROM iedb_taxa_view ORDER BY iedb_id"

for TABLE in epitope source object structure; do
  fetch "${TABLE}" "SELECT * FROM ${TABLE} ORDER BY ${TABLE}_id"
done

# Protect the files and directory from accidental change or deletion.
chmod a-w -R "${CACHE}"

echo "Linking current/iedb to ${CACHE}"
mkdir -p current
cd current || fail 'Could not cd to current/'
rm -f iedb
ln -s "../${CACHE}" iedb
