#!/bin/sh

# Fetch the IEDB data required by Arborist as TSV.

DATABASE=${1:?'Please provide a database name'}
CACHE="cache/${DATABASE}"

fail() {
  echo "ERROR: $1"
  exit 1
}

mkdir -p "${CACHE}/"
export MYSQL_DATABASE="${DATABASE}"

src/mysql2tsv \
	"SELECT ncbi_organism_id AS taxon_id FROM ncbi_organism_include WHERE ncbi_organism_id < 10000000 ORDER BY taxon_id" \
  "${CACHE}/ncbi_include.tsv" \
  || fail "Failed to fetch ncbi_include"

src/mysql2tsv \
  "SELECT * FROM iedb_taxa_view ORDER BY iedb_id" \
  "${CACHE}/iedb_taxa.tsv" \
  || fail "Failed to fetch iedb_taxa"

for TABLE in epitope source object structure_object; do
  src/mysql2tsv \
    "SELECT * FROM ${TABLE} ORDER BY ${TABLE}_id" \
    "${CACHE}/${TABLE}.tsv" \
    || fail "Failed to fetch $TABLE"
done

cd "cache/"
ln -s "${DATABASE}" "iedb"
